#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status ok

# Change to a writable directory
cd /tmp

# Check if the CloudWatch agent is already installed
if dpkg-query -W -f='${Status}' amazon-cloudwatch-agent 2>/dev/null | grep -q "ok installed"; then
    echo "CloudWatch agent is already installed."
else
    # Download the CloudWatch agent
    echo "Downloading CloudWatch agent..."
    if wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb; then
        echo "CloudWatch agent downloaded successfully."
    else
        echo "Failed to download CloudWatch agent."
        exit 1
    fi

    # Install the CloudWatch agent
    echo "Installing CloudWatch agent..."
    if sudo dpkg -i amazon-cloudwatch-agent.deb; then
        echo "CloudWatch agent installed successfully."
    else
        echo "Failed to install CloudWatch agent. Attempting to fix broken dependencies..."
        sudo apt-get -f install
    fi
fi

# Create the configuration directory if it doesn't exist
sudo mkdir -p /opt/aws/amazon-cloudwatch-agent/etc

# Set permissions for the CloudWatch agent directory
sudo chmod -R 755 /opt/aws/amazon-cloudwatch-agent

# Retrieve the CloudWatch log group name from EC2 tags
CWLOGGROUP=$(aws ec2 describe-tags --filters "Name=key,Values=APP_ENV" --query "Tags[0].Value" --output text)
echo "CWLOGGROUP: $CWLOGGROUP"

# Create the CloudWatch log group if it doesn't exist
echo "Creating CloudWatch log group..."
aws logs create-log-group --log-group-name "$CWLOGGROUP" || true

# Write the CloudWatch agent configuration
echo "Writing CloudWatch agent configuration..."
sudo bash -c 'cat << EOF > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
{
  "agent": {
    "metrics_collection_interval": 60,
    "logfile": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
  },
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log",
            "log_group_name": "'"$CWLOGGROUP"'",
            "log_stream_name": "{instance_id}",
            "timezone": "UTC"
          }
        ]
      }
    }
  }
}
EOF'

# Stop the CloudWatch agent if it's running
echo "Stopping CloudWatch agent..."
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a stop

# Start the CloudWatch agent
echo "Starting CloudWatch agent..."
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a start

# Clean up the downloaded .deb file
if [ -f amazon-cloudwatch-agent.deb ]; then
    echo "Cleaning up..."
    rm -f amazon-cloudwatch-agent.deb
fi

echo "CloudWatch agent setup completed successfully."
